[project]
name = "medical-dataset-processor"
version = "0.1.0"
description = "Automated medical dataset processing with translation and content generation"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv",
    "deepl",
    "openai",
    "pyyaml",
    "reportlab",
    "datasets"
]
